// generated by scripts/mksyscall.sh syscall/os/linux/syscall_linux_riscv.decl -- DO NOT EDIT

#include <u.h>
#include <libc.h>
#include "syscall_linux_riscv.h"

long write(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_write, (long)fd, (long)buf, (long)n, 0, 0, 0);
}

long read(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_read, (long)fd, (long)buf, (long)n, 0, 0, 0);
}

int close(int fd)
{
	return (int)_syscall6(SYS_close, (long)fd, 0, 0, 0, 0, 0);
}

int _sysllseek(int fd, ulong offhi, ulong offlo, vlong* result, int whence)
{
	return (int)_syscall6(SYS_llseek, (long)fd, (long)offhi, (long)offlo, (long)result, (long)whence, 0);
}

long openat(int dirfd, void* path, int flags, int mode)
{
	return (long)_syscall6(SYS_openat, (long)dirfd, (long)path, (long)flags, (long)mode, 0, 0);
}

int unlinkat(int dirfd, char* path, int flags)
{
	return (int)_syscall6(SYS_unlinkat, (long)dirfd, (long)path, (long)flags, 0, 0, 0);
}

int mkdirat(int dirfd, char* path, int mode)
{
	return (int)_syscall6(SYS_mkdirat, (long)dirfd, (long)path, (long)mode, 0, 0, 0);
}

int faccessat(int dirfd, char* path, int mode, int flags)
{
	return (int)_syscall6(SYS_faccessat, (long)dirfd, (long)path, (long)mode, (long)flags, 0, 0);
}

int _sysdup(int fd)
{
	return (int)_syscall6(SYS_dup, (long)fd, 0, 0, 0, 0, 0);
}

int dup3(int oldfd, int newfd, int flags)
{
	return (int)_syscall6(SYS_dup3, (long)oldfd, (long)newfd, (long)flags, 0, 0, 0);
}

int chdir(char* path)
{
	return (int)_syscall6(SYS_chdir, (long)path, 0, 0, 0, 0, 0);
}

void exit(int code)
{
	_syscall6(SYS_exit, (long)code, 0, 0, 0, 0, 0);
}

