// generated by scripts/mksyscall.sh syscall/os/linux/syscall_linux_386.decl -- DO NOT EDIT

#include <u.h>
#include <libc.h>
#include "syscall_linux_386.h"

long write(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_write, (long)fd, (long)buf, (long)n, 0, 0, 0);
}

void exit(int code)
{
	_syscall6(SYS_exit, (long)code, 0, 0, 0, 0, 0);
}

