// generated by scripts/mksyscall.sh syscall/os/linux/syscall_linux_amd64.decl -- DO NOT EDIT

#include <u.h>
#include <libc.h>
#include "syscall_linux_amd64.h"

long write(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_write, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

long read(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_read, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

int close(int fd)
{
	return (int)_syscall6(SYS_close, (vlong)fd, 0, 0, 0, 0, 0);
}

vlong lseek(int fd, vlong offset, int whence)
{
	return (vlong)_syscall6v(SYS_lseek, (vlong)fd, (vlong)offset, (vlong)whence, 0, 0, 0);
}

long _sysopen(void* path, int flags, int mode)
{
	return (long)_syscall6(SYS_open, (vlong)path, (vlong)flags, (vlong)mode, 0, 0, 0);
}

int _sysunlink(char* path)
{
	return (int)_syscall6(SYS_unlink, (vlong)path, 0, 0, 0, 0, 0);
}

int _sysrmdir(char* path)
{
	return (int)_syscall6(SYS_rmdir, (vlong)path, 0, 0, 0, 0, 0);
}

int _sysmkdir(char* path, int mode)
{
	return (int)_syscall6(SYS_mkdir, (vlong)path, (vlong)mode, 0, 0, 0, 0);
}

int access(char* path, int mode)
{
	return (int)_syscall6(SYS_access, (vlong)path, (vlong)mode, 0, 0, 0, 0);
}

int _sysdup(int fd)
{
	return (int)_syscall6(SYS_dup, (vlong)fd, 0, 0, 0, 0, 0);
}

int _sysdup2(int oldfd, int newfd)
{
	return (int)_syscall6(SYS_dup2, (vlong)oldfd, (vlong)newfd, 0, 0, 0, 0);
}

int chdir(char* path)
{
	return (int)_syscall6(SYS_chdir, (vlong)path, 0, 0, 0, 0, 0);
}

void exit(int code)
{
	_syscall6(SYS_exit, (vlong)code, 0, 0, 0, 0, 0);
}

uintptr _sysbrk(void* addr)
{
	return (uintptr)_syscall6v(SYS_brk, (vlong)addr, 0, 0, 0, 0, 0);
}

int getpid(void)
{
	return (int)_syscall6(SYS_getpid, 0, 0, 0, 0, 0, 0);
}

long _sysgetcwd(char* buf, ulong size)
{
	return (long)_syscall6(SYS_getcwd, (vlong)buf, (vlong)size, 0, 0, 0, 0);
}

int _sysclockgettime(int clockid, void* ts)
{
	return (int)_syscall6(SYS_clock_gettime, (vlong)clockid, (vlong)ts, 0, 0, 0, 0);
}

int _sysclocknanosleep(int clockid, int flags, void* req, void* rem)
{
	return (int)_syscall6(SYS_clock_nanosleep, (vlong)clockid, (vlong)flags, (vlong)req, (vlong)rem, 0, 0);
}

