// generated by scripts/mksyscall.sh syscall/os/linux/syscall_linux_riscv64.decl -- DO NOT EDIT

#include <u.h>
#include <libc.h>
#include "syscall_linux_riscv64.h"

long write(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_write, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

long read(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_read, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

int close(int fd)
{
	return (int)_syscall6(SYS_close, (vlong)fd, 0, 0, 0, 0, 0);
}

vlong lseek(int fd, vlong offset, int whence)
{
	return (vlong)_syscall6v(SYS_lseek, (vlong)fd, (vlong)offset, (vlong)whence, 0, 0, 0);
}

long openat(int dirfd, void* path, int flags, int mode)
{
	return (long)_syscall6(SYS_openat, (vlong)dirfd, (vlong)path, (vlong)flags, (vlong)mode, 0, 0);
}

int unlinkat(int dirfd, char* path, int flags)
{
	return (int)_syscall6(SYS_unlinkat, (vlong)dirfd, (vlong)path, (vlong)flags, 0, 0, 0);
}

int mkdirat(int dirfd, char* path, int mode)
{
	return (int)_syscall6(SYS_mkdirat, (vlong)dirfd, (vlong)path, (vlong)mode, 0, 0, 0);
}

int faccessat(int dirfd, char* path, int mode, int flags)
{
	return (int)_syscall6(SYS_faccessat, (vlong)dirfd, (vlong)path, (vlong)mode, (vlong)flags, 0, 0);
}

int _sysdup(int fd)
{
	return (int)_syscall6(SYS_dup, (vlong)fd, 0, 0, 0, 0, 0);
}

int dup3(int oldfd, int newfd, int flags)
{
	return (int)_syscall6(SYS_dup3, (vlong)oldfd, (vlong)newfd, (vlong)flags, 0, 0, 0);
}

int chdir(char* path)
{
	return (int)_syscall6(SYS_chdir, (vlong)path, 0, 0, 0, 0, 0);
}

void exit(int code)
{
	_syscall6(SYS_exit, (vlong)code, 0, 0, 0, 0, 0);
}

