TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=8l
LDLIBS=-lbio -l9 -lm

OFILES=\
	asm.$O\
	../ld/data.$O\
	../ld/dwarf.$O\
	../ld/elf.$O\
	enam.$O\
	../ld/go.$O\
	../ld/lib.$O\
	list.$O\
	../ld/macho.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	../ld/pe.$O\
	prof.$O\
	span.$O\
	symtab.$O\

HFILES=\
	l.h\
	../8l/8.out.h\
	../ld/dwarf.h\
	../ld/elf.h\
	../ld/macho.h\
	../ld/pe.h\

<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: 8.out.h
	sh mkenam
