TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

LIB=cc.a

OFILES=\
	y.tab.$O\
	lex.$O\
	mac.$O\
	dcl.$O\
	acid.$O\
	pickle.$O\
	bits.$O\
	com.$O\
	com64.$O\
	scon.$O\
	funct.$O\
	sub.$O\
	dpchk.$O\
	omachcap.$O\
        \
	mpatof.$O\

HFILES=cc.h y.tab.h

YFILES=cc.y

<$TOP/mkfiles/mklib

#mac.$O: macbody
#lex.$O:	lex.c
#	$CC $CFLAGS '-DCPP="/bin/cpp"' lex.c
