TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=6c
LDLIBS=-lbio -l9 -lm

OFILES=\
	cgen.$O\
	enam.$O\
	list.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
	reg.$O\
	peep.$O\
	pgen.$O\
	pswt.$O\
	machcap.$O\
	div.$O\
	mul.$O\

HFILES=	gc.h $TOP/include/6.out.h $TOP/compilers/cck/cc.h

LIB=$TOP/compilers/cck/cc.a

<$TOP/mkfiles/mkone

p%.$O: $TOP/compilers/cck/p%.c
	$CC $CFLAGS $TOP/compilers/cck/p$stem.c
