TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=acid
LDLIBS=-lmach -lbio -lregexp -l9 -lm

OFILES=	main.$O\
	y.tab.$O\
	lex.$O\
	util.$O\
	exec.$O\
	expr.$O\
	list.$O\
	builtin.$O\
	proc.$O\
	dot.$O\
	print.$O\
        \
	rdebug.$O\
        \
	os-Posix.$O\

YFILES=dbg.y
HFILES=acid.h y.tab.h

<$TOP/mkfiles/mkone

