TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

LDLIBS=-lbio -l9 -lm

#TODO: tee: miss atnotify, tail: miss p9sleep, mc: need draw.h,
# sort: miss tobaserune
TARG=uniq xargs p

<$TOP/mkfiles/mkmany

