TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

# for mc to remove plan9 specific draw.h and rio/acme extensions
CFLAGS_EXTRA=-DUnix
LDLIBS=-lbio -l9 -lm

TARG=xargs p mc tee tail

<$TOP/mkfiles/mkmany
