TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

# The directory is nm because the source is portable and general.
# We call the binary 6nm to avoid confusion with the host nm.

TARG=6nm
# need -lmach too here
LDLIBS=-lmach -lbio -l9 -lm

OFILES=\
	nm.$O\

<$TOP/mkfiles/mkone
