TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=kl
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	sched.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
        \
	enam.$O\
	elf.$O\
	compat.$O\

HFILES=	l.h $TOP/include/obj/k.out.h

<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: $TOP/include/obj/k.out.h
	sh mkenam

%.$O:	../lk/%.c
	$CC $CFLAGS ../lk/$stem.c

#enam.$O:	../kc/enam.c
#	$CC $CFLAGS ../kc/enam.c
