* Big plan

** TODO changes.txt
- SEMI fully working arm32 and arm64 mini2/
- SEMI hello_linux_riscv.exe and exit_linux_riscv.exe
- TODO revert the changes to va/vc/vl, ia/ic/il, 7a/7c/7l and switch
  from golang cc/ to kencc-imported cc/
- TODO switch acid, and 5i/vi from libmach_ to libmach

- bootstrappable (can compile itself)

** Overview

# fix float/64bits ops arm32 and arm64 tests/c/mini2
# produce from hello.{s,c} binaries for SEMI (old) macos (amd64 TODO arm64), (386) windows
# reLPize {Assembler,Linker,Compiler,Libcore}.nw and release (and maybe also {Debugger,Profiler}.nw) "principia-toolchain"!
# add wasm arch later and bootstrap itself!!!
# => simpler alt to gcc/clang for cross compiling C code! (ex: xv6-{x86,arm,riscv}!)

** Later

*** LATER LONG try to boostrap itself; can compile 5c with 5c?
need full libc and ELF in 5c/5l working for big C project, not just helloprintf.c

*** LATER devdraw from plan9port to goken? can draw ? can port
more stuff to unix? doomplan9?

maybe most of Graphics.nw can be tested on Linux?
at least testdraw.c ?

*** LATER SEMI try to unify all the kencc/inferno/plan9 before lpize (5a/5c/5l) again
diff5a diff5c diff5l are quite small across kencc/inferno/plan9 and goken
so no big need to unify. can start from goken probably which has the biggest change

use my diff.rc

*** LATER: start lpize again, redo the work in {Assembler,Linker,Compiler}.nw
relpize, resplit, but at least can reuse most of the thinking/splitting
work done for plan9
AND this time run regression tests first! to catch regression ASAP

update: with 5a_/5c_/5l_ working pretty good, maybe don't have
 to relpize actually and try 5a__/5c__/5l__ from principia's book
 and diff and gradually converge and fix bugs

alt: unless found bugs in plan9 toolchain and go towards merging with goken
codebase instead

*** LATER RELAX remove dead code like maxbecome/frame in linkers that was used for Alef
tail-call opti

*** LATER relax factorize in other linker ld.h like 7l
from l.h -> ld.h factorized
also 7l/{mod,pass,pobj,subr}.c can be moved to ../ld/
and factorize with other linkers
update: better ../lk/

but better wait to avoid diff.rc to show big diffs

* Last

*** continue switch to kencc code in goken

**** RELAX 5l/8l: cleanup the code like I did before with the '9',
the many dead -H xxx

**** RELAX add back -X to disable opti in 5c/8c
and try it on principia? still works?

**** use cc/ from kencc/plan9 instead of cc/ from golang cc/ for mips, arm64, riscv?
solves some of the weird behavior I get? for mips? for riscv? for arm64?

*** other goken PBS:

**** principia x goken x macos: compilation error "out of memory" on libsec/aes.c :(

***** WAITING run qemu with mkconfig.pc on clang and macos

**** principia x goken x thinkstation: pb mk nuke and bug in free() in rc
weird pbs when running 'mk nuke'
free(): invalid size

what is causing this error? rm? mk? rc?
seems to be pb with 'rc' because export MKSHELL=/opt/plan9/bin/rc
fixed the issue

does not have the problem in docker

**** mini2 x mips: pb for boolean showing false instead of true
can debug the code?
use cc_/ instead of cc/ ? better?

**** mini2 x arm__: -DDEBUG fails why?
happens with arm ?

**** mini2 x arm__: even with qemu-armhf I get some weird output for some floats
like 0.3333, or 20.0 that gets output as a super high float value, weird

2.2 is printed as -2.4+344/e-185

try kencc on it?
compare binary output? compare -S

seems to have same pb with arm arch :(

*** bug: why mk pdf in principia/linkers does not do the full
recipe and does not mv to generate Linker-7.pdf?

because mv of goken does not work :)
fix it!

#see the benefit of dogfooding and of goken easier to dogfood
#than principia!

*** RELAX look for sizeof(long) and fixed all of them!

*** RELAX remove sprint()! switch to sprint_DANGEROUS, then
maybe macro using sizeof() ? SPRINT() ? or use snprint and
pass length each time, safer

*** FUN try to use 6prof and 6cov

* Components

** ARM (kencc-imported) toolchain: 5a/5c/5l

*** still pbs on tests/c/float :( like for 5l__
weird float displayed

*** less: fix 5a to accept unicode like 5a_ and 5a__
TEXT ·getcallerpc(SB), $-4


*** test infra! run hello_plan9_arm.exe on raspberry pi2 via qemu?
need port principia to raspberry pi2 first then!

*** LATER factorize ld.a lib? imitate what I've done in principia?
hmm but l.h change each time so can do it?

*** LATER: merge with principia and fix regression in principia!
easier when will have test infra via qemu-system-arm

update: easier when goken 5a_/5c_/5l_ can work on linux
and can compile itself on linux => that's a good test suite

** hybrid ARM toolchain : 5a__/5c__/5l__

*** last

**** principia x goken x 5a__/5c__/5l__: pb dcl.c
5c -FTVw -I../../include/arch/arm -I../../include/ALL dcl.c
dcl.c:94 unknown vlong LIST
dcl.c:94 unknown vlong COND

reduce to minimal repro case? and then try kencc on it and compare
output?

better with cc_/ instead of cc/?

works with goken/kencc 5c at least! 
but then get back compilation error about floating
point error with linker (but maybe this one can be solved by long vs int32?)

**** diff 5l kencc vs 5l__ goken in obj.c
-	case AMOVDF:
-		if(!vfp || p->from.type != D_FCONST)
-			goto casedef;
-		p->as = AMOVF;
-		/* fall through */
 	case AMOVF:
 		if(skip)
 			goto casedef;
@@ -1225,7 +1191,7 @@ gethunk(void)

also hintabsize set correctly? also need dbuf[1] fix?

**** vfp set in 5l__ ? need -f ? for floating?

**** try use different VFP instructions for floats?
MOVF → VLDR/VMOV.F32/F64 + literal pool or immediate load).
something that my Ampere Altra can run?

look softfloat.c of 5l ? look 9front? more recent float instructions?


** golang ARM toolchain : 5a_/5c_/5l_

*** still? can't use 5c on principia libc code, weird!!!
wait.c:33 unknown type 15 in zaddr
can repro minimal case?
set principia/env.sh to point to goken/ROOT/arm64/bin/?

*** goken: get tests/c/mini2/helloprintf_nofloat_no64.exe working for 5a/5c/5l
linux_arm.s syscalls
but got segfault now :( even worse than before

update: better now that I made it work with 5l_ ?

** other golang toolchain

*** 8a_/8c_/8l_

**** principia x goken x 8a_/8c_/8l_: compilation error sysfatal.c
8c -FTVw -I../../../include/arch/386 -I../../../include/ALL sysfatal.c
sysfatal.c:27 rounding by 0


** C compilers: 5c/6c/8c

** assemblers: 5a/6a/8a

** linkers: 6l/6l/8l

** mk/rc

*** rc

**** regsub_ in Plan9.c and Posix.c
alt: adapt libregexp in principia to match the one in goken/kencc
right now in mk I need to adjust 

-                            regsub(pre->s, buf, /*sizeof(buf),*/ rmatch, NREGEXP);
+                            regsub(pre->s, buf, sizeof(buf), rmatch, NREGEXP);

**** LATER: port enough of :I: so can use goken mk for mk sync too!!!
so don't need to switch back and forth between kencc/goken mk
and xix mk

** libs

*** libcore

** Arch

*** arm_ (not arm__)

**** tests/c/mini2: run mk objtype=arm_ test_one in c/mini2/ too, remove NOSPLIT check
by using ifdef

but then with 5l requires sfloat in vlop.s, then sfloat2 in softfloat.c
and more stuff

*** arm (not arm_, not arm__)

*** arm64, 7a/7c/7l

**** fix tests/c/mini2/, first segfault and then restore the
local byte buf[100] in print_nofloat.c

**** add commits from 9front after initial import
lots of fixes from cinap probably worth taking

commit b29d5ac7b1f713e41285ad4b2ce1b23313d8088e
Author: cinap_lenrek <cinap_lenrek@felloff.net>
Date:   Mon Apr 8 13:45:49 2019 +0200

    add arm64 c compiler and assembler (thanks charles forsyth)
    
    this is the the initial sync of charles forsyths plan9 c
    compiler suite from http://bitbucket.org/plan9-from-bell-labs/9-cc
    at changeset version 54:65fb8bb56c59

**** 7c: restore typeswitch and neednewvlongcode stuff from cc.h and pgen.c
in 9-cc

useful?

**** get objdump to work on helloc_arm64.exe/helloc_arm_.exe too
what special thing we need to add in the elf binary?
it works for the arm32 binary with 5l but not 5l_

*** mips

**** tests/c/mini2: run mk objtype=mips test_one in c/mini2/
need extend minilibc.h to state uintptr for mips arch
and also need a linux_mips.s

**** helloprintf for mips

**** try vi on hello_plan9_mips.exe
error "can't read 4 bytes of symbol table"

**** can use acid to disassemble mips generated code and see it works?
as I can't use objdump


*** riscv 
#riscv and plan9!
# https://riscv.org/news/2020/10/a-plan-9-c-compiler-for-rv32gc-and-rv64gc/
# also xv6-riscv?

**** exit_linux_riscv.exe currently segfault

***** exit_linux_riscv64.s ? better?


**** riscv: hello_linux_riscv.exe (and test with qemu-riscv32)

***** hello_linux_riscv32.S for binutils to see the diff
with the one I'm generating

**** riscv: RELAX add also libmach code for i arch (riscv)
in 9front? in miller original tgz? in 9cc?

xinferno has it

try hello_linux_riscv.exe ?
try qemu to load it?
try acid on it?

** OSes

*** plan9 and goken

**** try tests/c/hello_plan9_arm.exe from .c!
mini libc

**** try tests/c/hello_plan9_mips.exe from .c!
mini libc

tests/c/mini2/ ?

*** make goken compile on Windows 386

**** make part of goken compile on windows
until 6g at least; even though sad that get runtime error when running 6g

***** fix weird compilation error in windows lib9/ that if you type make again
then it works the second time

**** hello_windows_x86.s
no simple sys.s like for darwin and linux :(
no interrupt and simple syscalls. Have to use this
stdcall complex thing and kernel32.dll and maybe complex setup

**** hello_windows_x86.c
try make hello.c that link with a few sys.s for windows and link for windows
maybe remove *.go in runtime/ and see if can build a runtime.a that
I can then use then to link a simple hello.c calling print.c

try rt0.8 and then 8l but then linking errors so missing stuff

**** try to fix 6g on Windows? still betypeinit error?

**** window.yml: try install mingw from windows-latest GHA job as experiment
so later can try to compile goken9cc in CI!

imitate some of the stuff in semgrep/.../build-windows-x86

** Debugger

*** SEMI port acid/ so can use it to dump the arm64/arm_ binaries!
and see the disassembled code.
right now objdump and llvm-dump and gdb do not work :(
(strace does at least)


*** FUN Debuggers.nw, try understand acid? and libmach? and add in goken?
there is a 9-cc/acid/ !
so it might be portable!
update: chatGPT says it actually can't debug live process :( or can just inspect
its state
maybe still useful though ...


*** acid fixes
# seems to work on 386, amd64, and arm_ hello_xxx binaries
arm64? 7db.c does not work?

**** RELAX acid can't load hello_plan9_mips.exe
because I didn't add v.c and vdb.c yet! (and vobj.c and vcodas.c)

**** acid can't decode file header for hello_linux_arm64.exe
and exit_linux_...

**** acid can't decode file header for hello_linux_arm.exe
and exit_linux_...

note that it can decode hello_linux_arm_.exe

weird because libmach relies on 5l/5.out.h, not 5l_/

***** merge 5l/ 5l_/ 5.out.h
because used then in libmach!

**** weird take long time to load on helloprintf_arm_.exe
and can't find any symbol except a weird "rue" ???

note that the program has an illegal instruction at runtime,
maybe this is the cause?

**** weird, acid can't show symbols on helloc_arm_.exe

*** port also db to goken
seems to be defined in plan9port

** GO stuff

*** FUN try run with qemu on bare hardware, try runtime/tiny target with qemu on x86
see also DELETED/misc/arm/ and the use of adb and maybe android emulator

**** try also the tiny/arm ? but no write :)

*** still? rerun the mkdefs, mksyscall, ... to generate the updated zxxx?
alt: take them from latest go repo and hope it's backward compatible?

** Rest (generators, utilities, typesetting)

*** goken/generators

**** RELAX LPize yaccpar too, and yaccpars
and sync in goken and principia

**** try to remove dependency to bison?
good though to also work with bison; it reports more bugs
than plan9 yacc and it's good to be compatible, just like
getting kencc to compile with gcc so easier to bootstrap.

*** goken/utilities/

**** RELAX LP split tr.c, join.c, sed.c, diff*.c
and also make it work on goken

**** make utilities work on goken

***** make grep compile and work on goken
Runemask ??

***** segfault on tar plan9port.tar
in fmt library, weird s pointer address
still?
tar cvf and xvf seems to work; maybe tvf has bugs

***** make tar and gunzip tar tvfz work on goken

***** make zip/unzip work on goken

***** awk: segfault
test: 
cd principia/kernel/COMPILE/bcm
export objtype=arm
export O=5
rc ../port/mkdevlist pi
rc ../port/mkbootrules pi


*** fix bugs in goken progs

**** bug goken 5i, does not seem to work on hello_plan9_arm.exe
compare to running 5i under plan9
bug in libmach? because 5i code in goken is the same than in principia

**** sync 5i with principia Machine.nw

**** bug goken mk/rc, adding lnrand.c to lib9/mkfile didn't trigger recompilation
use mk -dg
to debug and get graph of deps and time comparisons

does original mk better? maybe because if lib.a more recent
than lnrand.c, then it does not know. but lib.a depends on
OFILES so should have new OFILES and so should trigger recompilation
and re-archiving

update: fixed by mk -I (now the default) to remove intermediate deps opti?

**** bug mk sync in goken, does not modify the .nw actually
but then modify the .md5sum which then the next mk sync
just erase the modif because the orig .nw was not changed at the
step before

it creates a local Shell.nw! this is bad. need to fix syncweb probably

hard to reproduce, weird.
"orig Utilities.nw has been updated"

**** fix "Not consumed" in Make.nw, weird

*** goken/typesetting/

**** look at x9base/troff, smaller and self contained? can
produce postscript from simpler troff files like plan9.ms?

**** segfault on o.out lex when used from typesetting/grap

**** compile pic, tbl, etc. now that lex and yacc are there

**** LPize troff? eqn, tbl, pic, grap, tr2post, and page to visualize?
Documentation preparation system book
update: actually need postscript interpreter too; page calls gs which is huge

***** try generate end-to-end from hello.man e hello.ps
troff -man hello.man -Tutf | tr2post ?

***** still? first try troff and page on plan9
but can't work I think without aladin postscript. page is calling gs
and lp and tr2post

* Infra

** Test infra

*** use 5i/vi in mk test and in CI to run some hello_plan9_xxx programs?

*** testinfra: try make golang work for arm32? use armhf gcc and
compile the whole golang source tree and run the tests?
=> good regression test infra at least
see GO/all-arm and GO/tests/run-arm 

it compiles code with gcc (arm64), and we could adjust to arm-linux-gnueabihf-gcc
but I don't think it's the problem because then we get this error
at compile-time and don't even reach the testing part:

<epoch>: internal compiler error: betypeinit failed

*** LATER: try to compile goken with goken9cc!!!

*** More workflows! build_amd64_linux.yaml, build_amd64_windows
and test_xxx too ? alla semgrep workflows
start use jsonnet?

start multi GOOS and GOARCH in CI? in Docker can try all combinations?

** Build infra

*** less: get rid of dependency to byacc? use the included generators/yacc/yacc.c


*** switch to GOHOST and GOTARGET instead of GOARCH?
or GOARCHHOST, GOARCHTARGET, GOOSTARGET ?

*** still? switch from bison to yacc? so can work on plan9!
anyway I get bad errors about yerr.h that we could fix by switching to regular yacc!
update: seems to work already; I use yacc in my mkfile

*** LATER: try to compile goken9cc on plan9!!!!!
need VM then ... and need to find a way to transfer data from one to the other

*** still? support native windows (in Nt/) like in the original kencc?
needed?

** Bench infra

*** LATER add C tests and C bench for goken9cc
take the one from Leroy for compcert?

** Dev infra

*** devinfra: RELAX fix all gcc warnings in goken show when running 'mk'

*** can detect the ugly 'stdin' Binit in sed.c that
was fixed in inferno-os but caused some segfaults?
because stdin already defined elsewhere in goken lib9?

it was before -Wl,--allow-multiple-def

*** less: .gitignore inspired from DELETED/.hgignore

*** LATER betterfix the hack I put

**** fix gc/yerrxxx.h hack and yerr.h loadsys issue
and restore the syntax/ from the testsuite and other few tests

**** LATER: fix the many warnings reported by gcc and clang instead of using quietgcc
and abusing -Wno

** Internals

*** update from plan9?

*** update from inferno-os?
looks like it contains the latest portable sources
kencc and 9-cc seems not uptodate

but at the same time, I don't think it has 5a/5c/... synced
with the latest plan9 versions 
(which I did sync to get a working raspberry pi build of plan9)

*** update from 9front?

* Docs

** Misc

*** LATER read doc/asm.html in latest go and reference it from Assembler.nw
