TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=va
LDLIBS=-lbio -l9 -lm

OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	$TOP/linkers/vl/v.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

YFLAGS=-D1 -d

<$TOP/mkfiles/mkone

lex.$O:	$TOP/src/cmd/cc/macbody $TOP/src/cmd/cc/lexbody
