TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=5c_
LDLIBS=-lbio -l9 -lm

OFILES=\
	cgen.$O\
	list.$O\
	mul.$O\
	peep.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
        \
	pgen.$O\
	pswt.$O\
	../5l_/enam.$O\

HFILES=\
	gc.h\
	../5l_/5.out.h\
	../cc/cc.h\

LIB=../cc/cc.a

<$TOP/mkfiles/mkone

# have to use p% to restrict to pgen/pswt and not enam
# otherwise with just %.$O we get rule ambiguity
p%.$O: ../cc2/p%.c
	$CC $CFLAGS ../cc2/p$stem.c

