TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=2l
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	asm.$O\
	list.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
        \
	enam.$O\
	compat.$O\

HFILES=	l.h $TOP/include/obj/2.out.h

<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: $TOP/include/obj/z.out.h
	sh mkenam

%.$O:	../lk/%.c
	$CC $CFLAGS ../lk/$stem.c

#enam.$O:	../2c/enam.c
#	$CC $CFLAGS ../2c/enam.c
