TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=vl
LDLIBS=-lbio -l9 -lm

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	sched.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	\
        enam.$O\
	elf.$O\

#$TARGMODEL.$O\

HFILES= l.h v.out.h $TOP/include/ar.h

<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: v.out.h
	sh mkenam

%.$O:	../lk/%.c
	$CC $CFLAGS ../lk/$stem.c
