TOP=../../
<$TOP/mkfiles/$objtype/mkfile

TARG=ki
LDLIBS=-lmach -lbio $BOOTLIBS

OFILES=	ki.$O\
	run.$O\
	mem.$O\
	syscall.$O\
	stats.$O\
	icache.$O\
	symbols.$O\
	cmd.$O\
	bpt.$O\
	float.$O\

HFILES=sparc.h

<$TOP/mkfiles/mkone

acid:
	$CC -a run.c > acid.def
