TEXT _start+0(SB), $0
	// set up the static base (gp = REGSB = R29) so the global string
	// references generated by zc in main resolve -- same role as
	// setSB in start_arm64.s/start_riscv.s.
	MOVQ	$setSB(SB), R29
	JSR	,main+0(SB)
