TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=vl
LDLIBS=-lbio -l9 -lm
CFLAGS_EXTRA=-I../ld

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	sched.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
        enam.$O\

#$TARGMODEL.$O\
#elf.$O\

HFILES=\
	l.h\
	v.out.h\
	$TOP/include/ar.h\

<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: v.out.h
	sh mkenam

#elf.$O:	../ld/elf.c
#	$CC $CFLAGS ../ld/elf.c
#$TARGMODEL.$O:	../ld/$TARGMODEL.c
#	$CC $CFLAGS ../ld/$TARGMODEL.c
