TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

all:V: helloprintf.exe
clean:V:
	rm -f *.[5678ijv] *.exe *.a
test_one:V: all
	./helloprintf.exe

CPP_FLAGS=-D$objtype

# can use -v for verbose mode to help debug
helloprintf.exe: helloprintf.c
   $CC_ $CPP_FLAGS -c test.c
   $CC_ $CPP_FLAGS -c print_nofloat_no64.c
   $CC_ $CPP_FLAGS -c helloprintf.c
   $AS_ $CPP_FLAGS -c linux_$objtype.s
   iar rc libprint.a linux_$objtype.$O_ print*.$O_ test.$O_
   $LD_ -L. -o $target -E _main helloprintf.$O_

#TODO: arm arm64 386 riscv
#TODO: arm: works for the bool and hexa but not for 42; segfault
#TODO: mips: gives weird output, 'false' instead of 'true'
ARCHS=amd64 arm_ mips
test:V:
        for (arch in $ARCHS) {
           echo $arch
           mk clean
           mk 'objtype='$arch
	   if (~ $arch arm_)
	      qemu-armhf ./helloprintf.exe
           if not
	      qemu-$arch ./helloprintf.exe
        }

# useful when troubleshooting issues to just get rid of the use of iar and
# get rid of float/64 bits instructions and see if everything
# else works at least
helloprintf_nofloat_no64.exe: helloprintf.c
   $CC_ $CPP_FLAGS -c print_nofloat_no64.c
   $CC_ $CPP_FLAGS -c helloprintf.c
   $AS_ $CPP_FLAGS -c linux_$objtype.s
   #iar rc libprint.a linux_$objtype.$O_ print_nofloat_no64.$O_
   $LD_ -L. -o $target -E main helloprintf.$O_ linux_$objtype.$O_ print_nofloat_no64.$O_

helloprintf_arm_nofloat_no64.exe: helloprintf.c
   5c_ -Darm_ -c print_nofloat_no64.c
   5c_ -Darm_ -c helloprintf.c
   5a_ -Darm_ -c linux_arm.s
   5l_ -H7 -o $target -E _start helloprintf.5 linux_arm.5 print_nofloat_no64.5
