// Just a test file to see the code generated by 5c_/6c/...
// ex: 5c_ -S test.c => and look at the assembly output.

typedef	signed char            int8;
typedef	unsigned char			byte;

void
printf(int8 *s, ...)
{
	byte *arg;

	arg = (byte*)(&s+1);
	vprintf(s, arg);
}
