// Just a test file to see the code generated by 5c_/6c/...
// ex: 5c_ -S test.c => and look at the assembly output.

// from minilibc.h
typedef	signed char            int8;
typedef	unsigned char			byte;
typedef	unsigned long long		uint64;
typedef double float64;

static	uint64	uvnan		= 0x7FF0000000000001ULL;

//void
//printf(int8 *s, ...)
//{
//	byte *arg;
//	arg = (byte*)(&s+1);
//	vprintf(s, arg);
//}

float64 test_float(void) {
    return 2.2;
}

void test(void) {
    test_float();
}
