TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=ql
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	sched.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
        \
	enam.$O\
	elf.$O\
	compat.$O\
	cnam.$O\
	asmout.$O\

HFILES=	l.h $TOP/include/obj/q.out.h

<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: $TOP/include/obj/z.out.h
	sh mkenam

%.$O:	../lk/%.c
	$CC $CFLAGS ../lk/$stem.c

#enam.$O:	../qc/enam.c
#	$CC $CFLAGS ../qc/enam.c
#elf.$O:	../8l/elf.c
#	$CC $CFLAGS ../8l/elf.c
cnam.c:	l.h
	sh mkcname
