TOP=../../
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=vi
LDLIBS=-lmach_ -lbio -l9 -lm

OFILES=vi.$O\
	run.$O\
	special.$O\
	mem.$O\
	syscall.$O\
	stats.$O\
	icache.$O\
	symbols.$O\
	cmd.$O\
	bpt.$O\
	float.$O\

HFILES=mips.h

<$TOP/mkfiles/mkone

acid:	
	$CC -a run.c > acid.def
