<$TOP/mkfiles/mkfile.proto

# the goken cross-toolchain itself: used by tests/ (mk objtype=mips) and,
# once self-hosting is viable, as CC/AS/LD for the top-level build too
O=v
CC=vc
LD=vl
AS=va
AR=iar

CFLAGS=$CFLAGS_COMMON -I$TOP/include/arch/mips
