// generated by scripts/mksyscall.sh lib_core/libc/syscall/os/darwin/syscall_darwin_amd64.decl -- DO NOT EDIT

#include <u.h>
#include <libc.h>
#include "syscall_darwin_amd64.h"

long write(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_write, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

long read(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_read, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

int close(int fd)
{
	return (int)_syscall6(SYS_close, (vlong)fd, 0, 0, 0, 0, 0);
}

vlong lseek(int fd, vlong offset, int whence)
{
	return (vlong)_syscall6v(SYS_lseek, (vlong)fd, (vlong)offset, (vlong)whence, 0, 0, 0);
}

long _sysopen(void* path, int flags, int mode)
{
	return (long)_syscall6(SYS_open, (vlong)path, (vlong)flags, (vlong)mode, 0, 0, 0);
}

int _sysunlink(char* path)
{
	return (int)_syscall6(SYS_unlink, (vlong)path, 0, 0, 0, 0, 0);
}

int _sysrmdir(char* path)
{
	return (int)_syscall6(SYS_rmdir, (vlong)path, 0, 0, 0, 0, 0);
}

int _sysmkdir(char* path, int mode)
{
	return (int)_syscall6(SYS_mkdir, (vlong)path, (vlong)mode, 0, 0, 0, 0);
}

int access(char* path, int mode)
{
	return (int)_syscall6(SYS_access, (vlong)path, (vlong)mode, 0, 0, 0, 0);
}

int _sysdup(int fd)
{
	return (int)_syscall6(SYS_dup, (vlong)fd, 0, 0, 0, 0, 0);
}

int _sysdup2(int oldfd, int newfd)
{
	return (int)_syscall6(SYS_dup2, (vlong)oldfd, (vlong)newfd, 0, 0, 0, 0);
}

int chdir(char* path)
{
	return (int)_syscall6(SYS_chdir, (vlong)path, 0, 0, 0, 0, 0);
}

void exit(int code)
{
	_syscall6(SYS_exit, (vlong)code, 0, 0, 0, 0, 0);
}

uintptr _sysmmap(void* addr, ulong len, int prot, int flags, int fd, vlong offset)
{
	return (uintptr)_syscall6v(SYS_mmap, (vlong)addr, (vlong)len, (vlong)prot, (vlong)flags, (vlong)fd, (vlong)offset);
}

