// generated by scripts/mksyscall.sh syscall/os/darwin/syscall_darwin_amd64.decl -- DO NOT EDIT

#include <u.h>
#include <libc.h>
#include "syscall_darwin_amd64.h"

long write(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_write, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

long read(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_read, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

int close(int fd)
{
	return (int)_syscall6(SYS_close, (vlong)fd, 0, 0, 0, 0, 0);
}

vlong lseek(int fd, vlong offset, int whence)
{
	return (vlong)_syscall6v(SYS_lseek, (vlong)fd, (vlong)offset, (vlong)whence, 0, 0, 0);
}

long _sysopen(void* path, int flags, int mode)
{
	return (long)_syscall6(SYS_open, (vlong)path, (vlong)flags, (vlong)mode, 0, 0, 0);
}

void exit(int code)
{
	_syscall6(SYS_exit, (vlong)code, 0, 0, 0, 0, 0);
}

