// generated by scripts/mksyscall.sh syscall/os/darwin/syscall_darwin_arm64.decl -- DO NOT EDIT

#include <u.h>
#include <libc.h>
#include "syscall_darwin_arm64.h"

long write(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_write, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

void exit(int code)
{
	_syscall6(SYS_exit, (vlong)code, 0, 0, 0, 0, 0);
}

