TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

LDLIBS=-lbio -l9 -lm

#TODO: du: need lib_string, file: has pbs, iconv needs draw.h
# strings: rune pb, 
TARG=basename unicode wc

<$TOP/mkfiles/mkmany
