TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

# -lstring needed only for du
LDLIBS=-lstring -lbio -l9 -lm

#TODO: file: has pbs, iconv needs draw.h, strings: rune pb, 
TARG=basename wc unicode du

<$TOP/mkfiles/mkmany
