

// Code generated by 5c for arr and pt:
//	DATA	arr+0(SB)/1,$47
//	DATA	arr+1(SB)/1,$116
//	DATA	arr+2(SB)/1,$109
//	DATA	arr+3(SB)/1,$112
//	DATA	arr+4(SB)/1,$47
//	DATA	arr+5(SB)/1,$88
//	DATA	arr+6(SB)/1,$88
//	DATA	arr+7(SB)/1,$88
//	DATA	arr+8(SB)/1,$88
//	DATA	.string<>+0(SB)/8,$"\057tmp\057YYY"
//	DATA	pt+0(SB)/4,$.string<>+0(SB)
//	DATA	.string<>+8(SB)/8,$"Y\z\z\z\z\z\z\z"
//	GLOBL	arr+0(SB),$10
//	GLOBL	pt+0(SB),$4
//	GLOBL	.string<>+0(SB),$16
//	END	,
// => arr will be in writeable section of Data and pt
// will point to a string in .string (which I think the linker
// mark as read-only section sometimes with gcc)

// Code generated by gcc -S:
//	.arch armv8-a
//	.file	"string_array.c"
//	.text
//	.global	arr
//	.data
//	.align	3
//	.type	arr, %object
//	.size	arr, 10
//arr:
//	.string	"/tmp/XXXX"
//	.global	pt
//	.section	.rodata
//!!!!!!! .rodata here !!!!!!!
//	.align	3
//.LC0:
//	.string	"/tmp/YYYY"
//	.section	.data.rel.local,"aw"
//	.align	3
//	.type	pt, %object
//	.size	pt, 8
//pt:
//	.xword	.LC0
//	.ident	"GCC: (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0"
//	.section	.note.GNU-stack,"",@progbits



char	arr[] = "/tmp/XXXX";
char*   pt = "/tmp/YYYY";
