TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

LDLIBS=-lbio -l9

TARG=lex

OFILES=globals.$O\
        lmain.$O\
	y.tab.$O\
	sub1.$O\
	sub2.$O\
	header.$O\

HFILES=ldefs.h

# ugly? 
YACC=$TOP/generators/yacc/o.out

YFILES=parser.y

<$TOP/mkfiles/mkone

installall:V:
	for(objtype in $CPUS)
		mk install
	cp ncform /sys/lib/lex
