TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=8l
LDLIBS=-lbio -l9 -lm

OFILES=\
	asm.$O\
	list.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
        elf.$O\

#        compat.$O\
#	$TARGMODEL.$O\

HFILES= l.h 8.out.h  $TOP/include/ar.h


<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: 8.out.h
	sh mkenam

#%.$O:	../lk/%.c
#	$CC $CFLAGS ../lk/$stem.c

#enam.$O:	../8c/enam.c
#	$CC $CFLAGS ../8c/enam.c
