TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=iar	# inferno archiver
LDLIBS=-lmach_ -lbio -l9 -lm

OFILES=	ar.$O\

#	$TARGMODEL.$O\

HFILES=	$TOP/include/bio.h $TOP/include/mach.h

#$TOP/include/a.out.h\

<$TOP/mkfiles/mkone
