TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

# for ls to remove plan9 specific fcall.h
CFLAGS_EXTRA=-DUnix
# -lstring needed only for du
# -lbio needed only for wc
LDLIBS=-lbio -lstring -l9 -lm

# we skip 'cp' as mk install will lead to a "Text file busy" error
TARG=cat touch mkdir mv rm chmod chgrp mtime wc du ls

<$TOP/mkfiles/mkmany
#<$TOP/mkfiles/mkmanyauto
