TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

# for ls to remove plan9 specific fcall.h
CFLAGS_EXTRA=-DUnix
# -lstring needed only for du
# -lbio needed only for wc
LDLIBS=-lbio -lstring -l9 -lm

# let's not build cp and ls by default
# cp ls
TARG=cat touch mkdir mv rm chmod chgrp mtime wc du

<$TOP/mkfiles/mkmany
#<$TOP/mkfiles/mkmanyauto
