TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

LDLIBS=-lbio -l9 -lm

TARG=hoc

OFILES=\
	y.tab.$O\
	code.$O\
	init.$O\
	math.$O\
	symbol.$O\

HFILES=\
	y.tab.h\
	hoc.h\

YFILES=hoc.y

<$TOP/mkfiles/mkone
