TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=zl
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	sched.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
        \
	enam.$O\
	elf.$O\
	compat.$O\

HFILES=	l.h $TOP/include/obj/z.out.h

<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: $TOP/include/obj/z.out.h
	sh mkenam

%.$O:	../lk/%.c
	$CC $CFLAGS ../lk/$stem.c

#x:V:	$O.out
#	$O.out -la -o/dev/null x.7
#
#test:V:	$O.out
#	rm -f xxx
#	mv $O.out xxx
#	./xxx $OFILES
#	cmp $O.out xxx
