TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=6l
LDLIBS=-lbio -l9 -lm
OFILES=\
	asm.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	list.$O\
	enam.$O\
	compat.$O\
	elf.$O\

HFILES=\
	l.h\
	$TOP/include/6.out.h\
	../lk/elf.h\

<$TOP/mkfiles/mkone

enam.$O:	$TOP/compilers/6c/enam.c
	$CC $CFLAGS $TOP/compilers/6c/enam.c
elf.$O:	../lk/elf.c
	$CC $CFLAGS ../lk/elf.c
