#!/bin/sh
# Generates C syscall wrapper functions from a declarative "//sys" spec
# file, in the spirit of GO/pkg/syscall/mksyscall.sh's "//sys name(args)
# (ret) = SYS_NAME" comment convention -- adapted to C, and to a single
# generic 6-arg trampoline (every wrapper just calls _syscall6, padding
# unused argument slots with 0) rather than needing hand-written
# assembly per syscall or per arity.
#
# usage: mksyscall.sh some.decl > zsyscall_xxx.c
set -eu

if [ $# -ne 1 ]; then
	echo "usage: mksyscall.sh file.decl" >&2
	exit 1
fi

base=$(basename "$1" .decl)

echo "// generated by scripts/mksyscall.sh $1 -- DO NOT EDIT"
echo
echo "#include <u.h>"
echo "#include <libc.h>"
echo "#include \"$base.h\""
echo

awk '
/^\/\/sys[ \t]/ {
	line = $0
	sub(/^\/\/sys[ \t]+/, "", line)

	# split "name(params) rettype = SYS_NAME" into its three pieces
	popen = index(line, "(")
	pclose = index(line, ")")
	name = substr(line, 1, popen - 1)
	params = substr(line, popen + 1, pclose - popen - 1)
	rest = substr(line, pclose + 1)
	gsub(/^[ \t]+|[ \t]+$/, "", rest)

	neq = index(rest, "=")
	rettype = substr(rest, 1, neq - 1)
	sysname = substr(rest, neq + 1)
	gsub(/^[ \t]+|[ \t]+$/, "", rettype)
	gsub(/^[ \t]+|[ \t]+$/, "", sysname)

	n = split(params, plist, ",")
	argstr = ""
	callargs = ""
	nargs = 0
	for (i = 1; i <= n; i++) {
		p = plist[i]
		gsub(/^[ \t]+|[ \t]+$/, "", p)
		if (p == "")
			continue
		# the parameter name is the last whitespace-separated
		# token; the type is everything before it
		nsp = split(p, words, " ")
		pname = words[nsp]
		ptype = ""
		for (j = 1; j < nsp; j++)
			ptype = ptype (j > 1 ? " " : "") words[j]
		# a leading "*" on the name (e.g. "void *buf") belongs to
		# the type instead
		while (substr(pname, 1, 1) == "*") {
			ptype = ptype "*"
			pname = substr(pname, 2)
		}
		if (argstr != "")
			argstr = argstr ", "
		argstr = argstr ptype " " pname
		callargs = callargs ", (long)" pname
		nargs++
	}
	for (i = nargs; i < 6; i++)
		callargs = callargs ", 0"

	print rettype " " name "(" argstr ")"
	print "{"
	if (rettype == "void")
		print "\t_syscall6(" sysname callargs ");"
	else
		print "\treturn (" rettype ")_syscall6(" sysname callargs ");"
	print "}"
	print ""
}
' "$1"
