<$TOP/mkfiles/mkfile.proto

# A few flag explanations:
# - the -m32 to force 32bits arch
# - the -mfpmath=sse is to avoid mismatch when interpreting float literals
#   so that the compilation of tests/c/misc/f_1_e_126.c leads to same code
# - the --std=gnu89 otherwise can't compile with recent defaults for gcc/clang
CC=gcc -m32 -mfpmath=sse -sse2  -Wno-cpp --std=gnu89 -c
LD=gcc -Wl,--allow-multiple-definition
AS=gcc
O=o

# used in tests/
O_=6
CC_=6c
LD_=6l
AS_=6a
AR_=ar_
