<$TOP/mkfiles/mkfile.proto

# the goken cross-toolchain itself: used by tests/ (mk objtype=386) and,
# once self-hosting is viable, as CC/AS/LD for the top-level build too
O=8
CC=8c
LD=8l
AS=8a
AR=iar

CFLAGS=$CFLAGS_COMMON -I$TOP/include/arch/386
