TOP=../../
<$TOP/mkfiles/$objtype/mkfile

TARG=qi
LDLIBS=-lmach -lbio $BOOTLIBS

OFILES=	qi.$O\
	run.$O\
	mem.$O\
	syscall.$O\
	stats.$O\
	icache.$O\
	symbols.$O\
	cmd.$O\
	bpt.$O\
	float.$O\
	branch.$O\
	iu.$O\

HFILES=power.h

<$TOP/mkfiles/mkone

acid:
	$CC -a run.c > acid.def
