TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

all:V: helloprintf.exe
clean:V:
	rm -f *.[5678ijv] *.exe *.a
test_one:V: all
	./helloprintf.exe | cmp /dev/stdin helloprintf.expected.txt

CPP_FLAGS=-D$objtype

# can use -v for verbose mode to help debug
helloprintf.exe: helloprintf.c
   $CC_ $CPP_FLAGS -c vlrt.c
   $CC_ $CPP_FLAGS -c print.c
   $CC_ $CPP_FLAGS -c helloprintf.c
   $AS_ $CPP_FLAGS -c linux_$objtype.s
   $AR_ rc libprint.a linux_$objtype.$O_ print*.$O_ vlrt.$O_
   $LD_ -L. -o $target -E _main helloprintf.$O_

#TODO: arm_
ARCHS=amd64 arm arm64 arm__ mips riscv 386
test:V:
        for (arch in $ARCHS) {
           echo $arch
           mk clean
           mk 'objtype='$arch
	   if (~ $arch arm__)
	      qemu-armhf ./helloprintf.exe | cmp /dev/stdin helloprintf.expected.txt
           if not if (~ $arch riscv)
	      qemu-riscv32 ./helloprintf.exe | cmp /dev/stdin helloprintf.expected.txt
           if not if (~ $arch 386)
	      qemu-i386 ./helloprintf.exe | cmp /dev/stdin helloprintf.expected.txt
           if not
	      qemu-$arch ./helloprintf.exe | cmp /dev/stdin helloprintf.expected.txt
        }


# macOS arm64: Darwin syscall stubs, Mach-O (-H6), mandatory ad-hoc
# signature (see docs/notes_macos.txt). Runs natively on Apple Silicon.
helloprintf_macos_arm64.exe: helloprintf.c
   7c -Darm64 -c vlrt.c
   7c -Darm64 -c print.c
   7c -Darm64 -c helloprintf.c
   7a -Darm64 -c macos_arm64.s
   ar_ rc libprint.a macos_arm64.7 print*.7 vlrt.7
   7l -H6 -L. -o $target -E _main helloprintf.7
   if(~ `{uname} Darwin) codesign -s - -f $target

# runs natively on Apple Silicon (no qemu needed)
test_macos:V: helloprintf_macos_arm64.exe
	./helloprintf_macos_arm64.exe | cmp /dev/stdin helloprintf.expected.txt

