TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=qc
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	cgen.$O\
	list.$O\
	machcap.$O\
	peep.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
	mul.$O\
        \
	pgen.$O\
	pswt.$O\
	$TOP/linkers/ql/enam.$O\

HFILES=	gc.h $TOP/include/obj/q.out.h $TOP/compilers/cck/cc.h

LIB= $TOP/compilers/cck/cc.a$O

<$TOP/mkfiles/mkone

$LIB:
	cd ../cck
	mk all

# see 7c/mkfile for more info
p%.$O: $TOP/compilers/cck/p%.c
	$CC $CFLAGS $TOP/compilers/cck/p$stem.c

#t:V:	$O.out
#	$O.out -S t
#	$LD -o t.out t.$O
#	t.out
#
#enam.c:	q.out.h
#	rc mkenam
