TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=ic		# also makes jc (for riscv64)
LDLIBS=-lbio -l9 -lm

OFILES=\
	cgen.$O\
	list.$O\
	mul.$O\
	peep.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
	machcap.$O\
        \
	pgen.$O\
	pswt.$O\
	$TOP/linkers/il/enam.$O\

HFILES=	gc.h $TOP/linkers/il/i.out.h $TOP/src/cmd/cc/cc.h

LIB=$TOP/src/cmd/cc/cc.a

<$TOP/mkfiles/mkone

# see 7c/mkfile for more info
p%.$O: $TOP/src/cmd/cc/p%.c
	$CC $CFLAGS $TOP/src/cmd/cc/p$stem.c

# jc is the same binary as ic, just installed under a second name: ic's
# main() is the shared src/cmd/cc/lex.c one (used by 7c/vc/ic), which now
# has an argv[0]-basename check for 'j' before it calls ginit() (mirroring
# the ja/jl convention in assemblers/ia/mkfile, linkers/il/mkfile); ic's
# own ginit() (txt.c) picks up thechar='j' from that to select ewidth[TIND]
# and the typeword/typecmplx tables, same idea as compilers/7c/txt.c's
# ginit(), which -- being always arm64/64-bit -- does it unconditionally.
install:V:	$BIN/$TARG $BIN/jc
$BIN/jc:	$O.out
	cp $prereq $target
