TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=ic		# also makes jc (for riscv64)
LDLIBS=-lbio -l9 -lm

OFILES=\
	cgen.$O\
	list.$O\
	mul.$O\
	peep.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
	machcap.$O\
        \
	pgen.$O\
	pswt.$O\
	$TOP/linkers/il/enam.$O\

HFILES=	gc.h $TOP/linkers/il/i.out.h $TOP/src/cmd/cc/cc.h

LIB=$TOP/src/cmd/cc/cc.a

<$TOP/mkfiles/mkone

# see 7c/mkfile for more info
p%.$O: $TOP/src/cmd/cc/p%.c
	$CC $CFLAGS $TOP/src/cmd/cc/p$stem.c

#	lex.$O\
#TODO: trick for ic and jc
#lex.$O: ../cc/lex.c ../cc/y.tab.h
#	$CC -Dmain'='ccmain $CFLAGS ../cc/lex.c
#$ROOT/$OBJDIR/lib/libcc.a:
#	cd ../cc
#	mk $MKFLAGS install
#	mk $MKFLAGS clean
#../cc/y.tab.h: ../cc/cc.y
#	cd ../cc
#	mk $MKFLAGS y.tab.h
#
#
# NOT enabled yet, unlike ja/jl (assemblers/ia/mkfile, linkers/il/mkfile):
# ic's main() -- unlike ia's/il's -- has its argv[0]/-j thechar='j' selection
# entirely commented out (see the top of txt.c, "TODO: trick for ic and
# jc"); ginit() hardcodes thechar='i' unconditionally. Installing jc as-is
# would just be ic under a different name, silently emitting 32-bit riscv
# code while claiming to be the 64-bit compiler. Needs that main()/ginit()
# work (plus the typeswitch/typecmplx wiring the TODO next to it mentions)
# before this is safe to uncomment.
#install:V:	$BIN/jc
