// _syspipe for sparc -- hand-written instead of generated by
// mksyscall.sh from syscall_linux_sparc.decl. See that decl file's own
// comment for why: sparc's real kernel sys_pipe (sparc_pipe, confirmed
// against arch/sparc/kernel/sys_sparc.c) is NOT the normal
// pointer-argument shape every other arch's raw pipe syscall has --
// it takes no pointer at all, returning fd[0] as the plain syscall
// return value and fd[1] via regs->u_regs[UREG_I1] (our own R9/%o1).
// Same SunOS-heritage register-return quirk as mips's own sysm_pipe
// (arch/mips's own pipe wrapper sidesteps it by using SYS_pipe2
// instead -- not available here: this port targets an older kernel
// tree that predates pipe2, see notes_arch_sparc.txt).
//
// R1 (REGSP) collides with the real hardware %g1, the syscall-number
// register -- same save/restore-around-the-trap dance as svc_sparc.s's
// own _syscall6, duplicated on both paths for the same "kl doesn't
// honor delay-slot placement" reason that file's own comment explains.
TEXT _syspipe(SB), $0
	MOVW	R7, R11			// save caller's int* fd (arrives in REGARG=R7) before the trap clobbers R7
	MOVW	R1, R14			// save REGSP before clobbering it
	MOVW	$42, R1			// SYS_pipe (numbers_sparc.h) -- hardcoded, this file can't #include headers (see svc_sparc.s's own precedent)
	MOVW	$0x10, R7
	TA	R7
	BCC	ok
	MOVW	R14, R1
	SUB	R8, R0, R7		// error: R7 = 0 - errno (see svc_sparc.s's own comment on why not "SUB R0,R8,R7")
	RETURN
ok:
	MOVW	R14, R1
	MOVW	R8, 0(R11)		// fd[0] = sparc_pipe's own return value
	MOVW	R9, 4(R11)		// fd[1] = sparc_pipe's own u_regs[UREG_I1] (R9/%o1)
	MOVW	$0, R7
	RETURN
