/* _sysrtsigaction for sparc -- hand-written instead of generated by
 * mksyscall.sh from syscall_linux_sparc.decl. See that decl file's own
 * comment for why: sparc's real kernel sys_rt_sigaction (confirmed
 * against arch/sparc/kernel/sys_sparc.c) takes FIVE arguments (sig,
 * act, oact, restorer, sigsetsize) -- every other Linux arch here
 * takes four (no restorer). Rather than change os/linux/notify.c
 * (arch-independent, shared by every arch) to pass a 5th argument only
 * sparc needs, this file keeps the same 4-arg C signature notify.c
 * already calls and inserts restorer=0 itself before falling through
 * to the shared _syscall6 trampoline. restorer=0/nil works because
 * this port doesn't register a SA_RESTORER-style trampoline for sparc
 * (unlike amd64/386 -- see notify.c's own SA_RESTORER_VAL comment);
 * the kernel only dereferences restorer when SA_RESTORER is set in
 * sa_flags, which this port never sets on sparc.
 */
#include <u.h>
#include <libc.h>
#include "syscall/os/linux/numbers_sparc.h"

/* Not including syscall_linux_sparc.h itself: it #includes
 * "numbers_sparc.h" with a bare relative name that only resolves when
 * compiled from within syscall/os/linux/ (like the generated
 * zsyscall_linux_sparc.c is) -- not from here in arch/sparc/. Declare
 * _syscall6 directly instead, same extern every arch's own
 * syscall_linux_$cputype.h carries. */
extern long _syscall6(long num, long a1, long a2, long a3, long a4, long a5, long a6);

int
_sysrtsigaction(int sig, void *act, void *oact, long sigsetsize)
{
	return _syscall6(SYS_rt_sigaction, sig, (long)act, (long)oact, 0, sigsetsize, 0);
}
