TOP=../../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

# -l9 just for chartorune
# -lm just for a few math functions
LDLIBS=-l9 -lm

TARG=awk
OFILES=re.$O\
	lex.$O\
	main.$O\
	parse.$O\
	proctab.$O\
	tran.$O\
	lib.$O\
	run.$O\
	y.tab.$O\

HFILES=awk.h\
	y.tab.h\
	proto.h\

YFILES=awkgram.y

<$TOP/mkfiles/mkone

proctab.c: y.tab.h maketab.c $O.maketab
	   ./$O.maketab > proctab.c

$O.maketab: maketab.$O
	   $LD $LDFLAGS -o $target $prereq $LDLIBS

maketab.$O: maketab.c
	    $CC $CFLAGS $CFLAGS_EXTRA maketab.c

CLEANFILES=$O.maketab proctab.c

#CFLAGS=-FTV -c -D_REGEXP_EXTENSION -D_RESEARCH_SOURCE -D_BSD_EXTENSION -DUTF
#YFLAGS=-S -d -v
#CC=pcc
#LD=pcc
#cpuobjtype=`{sed -n 's/^O=//p' /$cputype/mkfile}
#
#y.tab.h awkgram.c:	$YFILES
#	$YACC -o awkgram.c $YFLAGS $prereq
#proctab.c:	$cpuobjtype.maketab
#	./$cpuobjtype.maketab >proctab.c
#$cpuobjtype.maketab:	y.tab.h maketab.c
#	objtype=$cputype
#	mk maketab.$cputype
#maketab.$cputype:V:	y.tab.h maketab.$O
#	$LD -o $O.maketab maketab.$O
